version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/examples/transform-amd-to-commonjs-example"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
